export const eventsStatsCards = [
  {
    id: 1,
    title: "Total Events",
    value: "4",
    icon: "Calendar",
    iconColor: "#3ADFFA",
    iconBg: "rgba(58, 223, 250, 0.15)"
  },
  {
    id: 2,
    title: "Ticket Revenue",
    value: "৳703k",
    icon: "Wallet",
    iconColor: "#34C759",
    iconBg: "rgba(52, 199, 89, 0.15)"
  },
  {
    id: 3,
    title: "Ticket Sold",
    value: "1300",
    icon: "Ticket",
    iconColor: "#CC97FF",
    iconBg: "rgba(204, 151, 255, 0.15)"
  },
  {
    id: 4,
    title: "Completed",
    value: "12",
    icon: "CheckCircle",
    iconColor: "#34C759",
    iconBg: "rgba(52, 199, 89, 0.15)"
  }
]

export const eventsList = [
  {
    id: 1,
    title: "Neon City Arena",
    artist: "DJ Kaelen",
    genre: "Synthwave",
    venue: "Neon City Arena",
    city: "Tokyo, Japan",
    eventDate: "2026-11-24",
    eventTime: "20:00",
    ticketPrice: 500,
    totalTickets: 500,
    ticketsSold: 320,
    revenue: "160.0k",
    status: "Upcoming",
    cover: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&q=80&w=400",
    description: "Neon City Arena — a synthwave-drenched night of live sets and immersive visuals in the heart of Tokyo."
  },
  {
    id: 2,
    title: "The Grid Pavilion",
    artist: "Pulse Collective",
    genre: "Electronic",
    venue: "The Grid Pavilion",
    city: "Berlin, Germany",
    eventDate: "2026-11-12",
    eventTime: "21:00",
    ticketPrice: 350,
    totalTickets: 300,
    ticketsSold: 180,
    revenue: "63.0k",
    status: "Upcoming",
    cover: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?auto=format&fit=crop&q=80&w=400",
    description: "An underground electronic showcase from Pulse Collective inside Berlin's iconic Grid Pavilion."
  },
  {
    id: 3,
    title: "Sphere One",
    artist: "Nova Sterling",
    genre: "Pop",
    venue: "O2 Arena",
    city: "London, UK",
    eventDate: "2026-12-15",
    eventTime: "19:30",
    ticketPrice: 600,
    totalTickets: 300,
    ticketsSold: 300,
    revenue: "180.0k",
    status: "Sold Out",
    cover: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&q=80&w=400",
    description: "Nova Sterling brings the Sphere One world tour to a completely sold-out night at the O2 Arena."
  },
  {
    id: 4,
    title: "Flok Wind Dreams 2026",
    artist: "Bipul Akter",
    genre: "Folk",
    venue: "Army Stadium",
    city: "Dhaka, Bangladesh",
    eventDate: "2026-10-12",
    eventTime: "18:00",
    ticketPrice: 500,
    totalTickets: 300,
    ticketsSold: 192,
    revenue: "96.0k",
    status: "Upcoming",
    cover: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&q=80&w=400",
    description: "Flok Wind Dreams 2026 — an evening of folk storytelling and live acoustic performances at Army Stadium."
  },
  {
    id: 5,
    title: "TAHSIN Live in Dhaka",
    artist: "Tahsin Ahmed",
    genre: "Pop",
    venue: "International Convention City Bashundhara",
    city: "Dhaka, Bangladesh",
    eventDate: "2026-07-15",
    eventTime: "21:10",
    ticketPrice: 500,
    totalTickets: 5000,
    ticketsSold: 4820,
    revenue: "2.41M",
    status: "Under Review",
    cover: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=400",
    description: "TAHSIN Live in Dhaka at International Convention City Bashundhara. Experience an unforgettable night of music."
  },
  {
    id: 6,
    title: "Echo Nights Festival",
    artist: "Various Artists",
    genre: "EDM",
    venue: "Bashundhara Convention Center",
    city: "Dhaka, Bangladesh",
    eventDate: "2026-08-12",
    eventTime: "22:00",
    ticketPrice: 800,
    totalTickets: 1000,
    ticketsSold: 950,
    revenue: "760.0k",
    status: "Live",
    cover: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=400",
    description: "Echo Nights Festival is live right now — a multi-stage EDM celebration running through the night."
  },
  {
    id: 7,
    title: "Summer Beats Carnival",
    artist: "Various Artists",
    genre: "Pop",
    venue: "M A Aziz Stadium",
    city: "Chittagong, Bangladesh",
    eventDate: "2026-05-20",
    eventTime: "17:00",
    ticketPrice: 400,
    totalTickets: 2000,
    ticketsSold: 1850,
    revenue: "740.0k",
    status: "Completed",
    cover: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&q=80&w=400",
    description: "Summer Beats Carnival wrapped up with a record turnout across two stages in Chittagong."
  },
  {
    id: 8,
    title: "Midnight Rave Sessions",
    artist: "Unknown Organizer",
    genre: "Techno",
    venue: "Sylhet Convention Hall",
    city: "Sylhet, Bangladesh",
    eventDate: "2026-09-05",
    eventTime: "23:00",
    ticketPrice: 300,
    totalTickets: 500,
    ticketsSold: 0,
    revenue: "0.0k",
    status: "Rejected",
    cover: "https://images.unsplash.com/photo-1571266028243-d220c9c3b31d?auto=format&fit=crop&q=80&w=400",
    description: "Submission rejected — venue capacity documentation was incomplete."
  },
  {
    id: 9,
    title: "Studio Sessions Vol. 3",
    artist: "TAHSIN",
    genre: "Acoustic",
    venue: "TBD",
    city: "Dhaka, Bangladesh",
    eventDate: "-",
    eventTime: "-",
    ticketPrice: 200,
    totalTickets: 150,
    ticketsSold: 0,
    revenue: "0.0k",
    status: "Draft",
    cover: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?auto=format&fit=crop&q=80&w=400",
    description: "An intimate acoustic set — details still being finalized."
  }
]
