export const podcastsStatsCards = [
  {
    id: 1,
    title: "Total Episodes",
    value: "42",
    icon: "Headphones",
    iconColor: "#3ADFFA",
    iconBg: "rgba(58, 223, 250, 0.15)"
  },
  {
    id: 2,
    title: "Total Listeners",
    value: "320k",
    icon: "Users",
    iconColor: "#34C759",
    iconBg: "rgba(52, 199, 89, 0.15)"
  },
  {
    id: 3,
    title: "Avg Duration",
    value: "42min",
    icon: "Mic",
    iconColor: "#CC97FF",
    iconBg: "rgba(204, 151, 255, 0.15)"
  },
  {
    id: 4,
    title: "Active Series",
    value: "3",
    icon: "Clock",
    iconColor: "#FFAE00",
    iconBg: "rgba(254, 174, 0, 0.15)"
  }
]

export const podcastsList = [
  {
    id: 1,
    title: "Bangladesh Tech Weekly",
    duration: "45:00",
    artist: "Arif Hossain",
    series: "Tech BD",
    genre: "Technology",
    streams: "28.4K",
    released: "2026-01-24",
    status: "Published",
    cover: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=150",
    season: "2",
    episode: "14",
    listeners: "28.4K",
    description: "Bangladesh Tech Weekly — episode 14 of Tech BD, season 2, hosted by Arif Hossain. Category: Technology.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "230MB", format: "MP3" }
  },
  {
    id: 2,
    title: "Startup Stories BD",
    duration: "58:09",
    artist: "TAHSIN",
    series: "Business BD",
    genre: "Business",
    streams: "2.8M",
    released: "2026-01-24",
    status: "Published",
    cover: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=150",
    season: "3",
    episode: "14",
    listeners: "19.2K",
    description: "Inspirational stories from startup founders in Bangladesh discussing early challenges and key milestones.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "120MB", format: "MP3" }
  },
  {
    id: 3,
    title: "Mindful Living",
    duration: "34:34",
    artist: "TAHSIN",
    series: "Cyber-Neon Dreams",
    genre: "Health",
    streams: "6.8M",
    released: "2026-01-24",
    status: "Published",
    cover: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&q=80&w=150",
    season: "1",
    episode: "2",
    listeners: "11.6K",
    description: "Actionable tips for slow living, minimalism, and focus in a hyper-connected society.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "85MB", format: "MP3" }
  },
  {
    id: 4,
    title: "History of Bengal",
    duration: "34:44",
    artist: "TAHSIN",
    series: "Cyber-Neon Dreams",
    genre: "History",
    streams: "0",
    released: "-",
    status: "Draft",
    cover: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=150",
    season: "2",
    episode: "3",
    listeners: "0",
    description: "Deep dive into ancient Bengal dynasties, folklore, and structural archaeological sites.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "135MB", format: "MP3" }
  },
  {
    id: 5,
    title: "Film Talk BD",
    duration: "4:20",
    artist: "TAHSIN",
    series: "Single",
    genre: "Entertainment",
    streams: "0",
    released: "2026-01-24",
    status: "Scheduled",
    cover: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=150",
    season: "5",
    episode: "4",
    listeners: "0",
    description: "Behind the scenes talk of local cinema, independent filmmaking, and script reviews.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "110MB", format: "MP3" }
  },
  {
    id: 6,
    title: "Neon Horizon",
    duration: "45:20",
    artist: "TAHSIN",
    series: "Wellness",
    genre: "Health",
    streams: "5.4K",
    released: "2026-01-18",
    status: "Under Review",
    cover: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=150",
    season: "3",
    episode: "5",
    listeners: "5.4K",
    description: "A podcast exploring ambient lifestyle trends, digital mental wellness, and finding focus in an urban neon landscape.",
    isExplicit: true,
    audioFile: { name: "Audio file Seasonal", size: "90MB", format: "MP3" }
  },
  {
    id: 7,
    title: "Sylhet Nights",
    duration: "22:12",
    artist: "TAHSIN",
    series: "Single",
    genre: "R&B",
    streams: "0",
    released: "-",
    status: "Rejected",
    cover: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&q=80&w=150",
    season: "1",
    episode: "1",
    listeners: "0",
    description: "Late night conversations on music, culture, and life in Sylhet.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "60MB", format: "MP3" }
  },
  {
    id: 8,
    title: "Amar Hote Hote",
    duration: "31:58",
    artist: "TAHSIN",
    series: "Amar Hote Hote",
    genre: "Business",
    streams: "12.3K",
    released: "2026-01-10",
    status: "Take Down",
    cover: "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?auto=format&fit=crop&q=80&w=150",
    season: "1",
    episode: "8",
    listeners: "12.3K",
    description: "Conversations on personal growth and reinvention.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "95MB", format: "MP3" }
  },
  {
    id: 9,
    title: "Dhaka After Dark",
    duration: "40:15",
    artist: "TAHSIN",
    series: "Tech BD",
    genre: "Technology",
    streams: "8.1K",
    released: "2026-01-05",
    status: "Published",
    cover: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=150",
    season: "2",
    episode: "15",
    listeners: "8.1K",
    description: "Exploring the city's nightlife, culture and hidden gems.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "100MB", format: "MP3" }
  },
  {
    id: 10,
    title: "The Long Way Home",
    duration: "27:40",
    artist: "TAHSIN",
    series: "Wellness",
    genre: "Health",
    streams: "0",
    released: "-",
    status: "Draft",
    cover: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?auto=format&fit=crop&q=80&w=150",
    season: "3",
    episode: "6",
    listeners: "0",
    description: "Reflections on travel, distance, and finding home.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "80MB", format: "MP3" }
  },
  {
    id: 11,
    title: "Business Beats",
    duration: "36:22",
    artist: "TAHSIN",
    series: "Business BD",
    genre: "Business",
    streams: "0",
    released: "2026-02-10",
    status: "Scheduled",
    cover: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&q=80&w=150",
    season: "3",
    episode: "15",
    listeners: "0",
    description: "Weekly roundup on business trends across South Asia.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "105MB", format: "MP3" }
  },
  {
    id: 12,
    title: "Cinema Circle",
    duration: "38:05",
    artist: "TAHSIN",
    series: "Single",
    genre: "Entertainment",
    streams: "22.9K",
    released: "2025-12-28",
    status: "Published",
    cover: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&q=80&w=150",
    season: "1",
    episode: "13",
    listeners: "22.9K",
    description: "A roundtable on the latest in film and television.",
    isExplicit: false,
    audioFile: { name: "Audio file Seasonal", size: "115MB", format: "MP3" }
  }
]
