export const adminRolesStatsCards = [
  {
    id: "total-admin-users",
    title: "Total Admin Users",
    value: "23",
    icon: "TotalAdminUsersIcon",
    iconBg: "rgba(58, 223, 250, 0.1)",
    iconColor: "#3ADFFA",
    layout: "vertical",
  },
  {
    id: "active-roles",
    title: "Active Roles",
    value: "6",
    icon: "ShieldRoleIcon",
    iconBg: "rgba(52, 199, 89, 0.1)",
    iconColor: "#34C759",
    layout: "vertical",
  },
  {
    id: "pending-invites",
    title: "Pending Invites",
    value: "2",
    icon: "PendingInvitesIcon",
    iconBg: "rgba(204, 151, 255, 0.1)",
    iconColor: "#CC97FF",
    layout: "vertical",
  },
];

export const adminRoleCardsData = [
  {
    id: "ecommerce-manager",
    title: "E-commerce Manager",
    membersCount: "2 members",
    badgeBg: "rgba(237, 16, 16, 0.12)",
    badgeColor: "#FF8C8C",
    badgeBorder: "rgba(237, 16, 16, 0.25)",
    iconBg: "rgba(237, 16, 16, 0.15)",
    iconColor: "#FF6E84",
    permissions: [
      "Products Management",
      "Inventory Control",
      "Order Management",
      "Coupon Management",
    ],
    members: ["Ritu Sharma", "+1 more"],
  },
  {
    id: "super-admin",
    title: "Super Admin",
    membersCount: "2 members",
    badgeBg: "rgba(58, 223, 250, 0.12)",
    badgeColor: "#3ADFFA",
    badgeBorder: "rgba(58, 223, 250, 0.25)",
    iconBg: "rgba(58, 223, 250, 0.15)",
    iconColor: "#3ADFFA",
    permissions: [
      "Full System Control",
      "Settings Management",
      "Artist Management",
      "User Management",
      "Analytics Access",
      "Payment Management",
    ],
    members: ["Nadia Islam", "Rafiq Ahmed"],
  },
  {
    id: "finance-admin",
    title: "Finance Admin",
    membersCount: "3 members",
    badgeBg: "rgba(52, 199, 89, 0.12)",
    badgeColor: "#34C759",
    badgeBorder: "rgba(52, 199, 89, 0.25)",
    iconBg: "rgba(52, 199, 89, 0.15)",
    iconColor: "#34C759",
    permissions: [
      "Subscription Management",
      "Revenue Management",
      "Royalty Processing",
      "Artist Payout",
      "Refund Processing",
    ],
    members: ["Arif Rahman", "+1 more"],
  },
  {
    id: "customer-support",
    title: "Customer Support",
    membersCount: "2 members",
    badgeBg: "rgba(255, 174, 0, 0.12)",
    badgeColor: "#FFAE00",
    badgeBorder: "rgba(255, 174, 0, 0.25)",
    iconBg: "rgba(255, 174, 0, 0.15)",
    iconColor: "#FFAE00",
    permissions: [
      "Support Tickets",
      "Complaint Handling",
      "Verification Issues",
      "Basic User Management",
    ],
    members: ["Nadia Islam", "Rafiq Ahmed"],
  },
  {
    id: "content-moderator",
    title: "Content Moderator",
    membersCount: "3 members",
    badgeBg: "rgba(204, 151, 255, 0.12)",
    badgeColor: "#CC97FF",
    badgeBorder: "rgba(204, 151, 255, 0.25)",
    iconBg: "rgba(204, 151, 255, 0.15)",
    iconColor: "#CC97FF",
    permissions: [
      "Content Review",
      "Artist Verification Review",
      "Approve/Reject Artist",
      "Playlist Management",
    ],
    members: ["Arif Rahman", "+1 more"],
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    membersCount: "2 members",
    badgeBg: "rgba(231, 255, 196, 0.12)",
    badgeColor: "#E7FFC4",
    badgeBorder: "rgba(231, 255, 196, 0.25)",
    iconBg: "rgba(231, 255, 196, 0.15)",
    iconColor: "#E7FFC4",
    permissions: [
      "Homepage Promotion",
      "Featured Artists",
      "Campaign Management",
      "Push Notifications",
    ],
    members: ["Nadia Islam", "Rafiq Ahmed"],
  },
];
