export const adminSubscriptionsStatsCards = [
  {
    id: "total-subscribers",
    title: "Total Subscribers",
    value: "10M",
    icon: "Users",
    iconBg: "rgba(204, 151, 255, 0.1)",
    iconColor: "#CC97FF",
    layout: "vertical",
  },
  {
    id: "premium-users",
    title: "Premium Users",
    value: "1",
    icon: "Crown",
    iconBg: "rgba(58, 223, 250, 0.1)",
    iconColor: "#3ADFFA",
    layout: "vertical",
  },
  {
    id: "monthly-revenue",
    title: "Monthly Revenue",
    value: "৳626",
    icon: "Wallet",
    iconBg: "rgba(52, 199, 89, 0.1)",
    iconColor: "#34C759",
    layout: "vertical",
  },
  {
    id: "new-this-month",
    title: "New This Month",
    value: "300k",
    icon: "TrendingUp",
    iconBg: "rgba(52, 199, 89, 0.1)",
    iconColor: "#34C759",
    layout: "vertical",
  },
];

export const adminSubscriptionPlansData = [
  {
    id: "free",
    name: "Free",
    subscribers: "6.2M",
    devices: "1",
    trial: "-",
    price: "৳0",
    period: "/month",
    features: [
      { text: "Ad-supported listening", included: true },
      { text: "Offline mode", included: false },
      { text: "Hi-Fi Spatial Audio", included: false },
    ],
  },
  {
    id: "premium",
    name: "Premium",
    subscribers: "2.2M",
    devices: "1",
    trial: "7d",
    price: "৳200",
    period: "/month",
    features: [
      { text: "Ad-free experience", included: true },
      { text: "Unlimited offline mode", included: true },
      { text: "Lossless Hi-Fi Audio", included: true },
      { text: "Listen on any device", included: true },
    ],
  },
  {
    id: "family",
    name: "Family",
    subscribers: "0.9M",
    devices: "6",
    trial: "7d",
    price: "৳500",
    period: "/month",
    features: [
      { text: "All Premium features", included: true },
      { text: "Kids-only safe app", included: true },
      { text: "Up to 6 accounts", included: true },
    ],
  },
  {
    id: "student",
    name: "Student",
    subscribers: "0.5M",
    devices: "1",
    trial: "30d",
    price: "৳100",
    period: "/month",
    features: [
      { text: "Verified student discount", included: true },
      { text: "All Premium features", included: true },
      { text: "Hulu & Showtime access", included: true },
    ],
  },
];

export const adminMrrGrowthData = [
  { name: "Jul", value: 90 },
  { name: "Aug", value: 110 },
  { name: "Sep", value: 190 },
  { name: "Oct", value: 155 },
  { name: "Nov", value: 145 },
  { name: "Dec", value: 190 },
];

export const adminPlanDistributionData = [
  { name: "Free", value: 2, color: "#6B6B6B" },
  { name: "Premium", value: 3, color: "#3ADFFA" },
  { name: "Family", value: 1, color: "#CC97FF" },
  { name: "Students", value: 38, color: "#34C759" },
];

export const adminSubscribersListData = [
  {
    id: "1",
    name: "Iqbal Hasan",
    avatar: "",
    plan: "Premium",
    amount: "৳149/mo",
    status: "Active",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    autoRenew: true,
  },
  {
    id: "2",
    name: "Younus Akon",
    avatar: "",
    plan: "Free",
    amount: "৳0",
    status: "Active",
    startDate: "--",
    endDate: "--",
    autoRenew: false,
  },
  {
    id: "3",
    name: "Nazibulla",
    avatar: "",
    plan: "Family",
    amount: "৳149/mo",
    status: "Active",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    autoRenew: true,
  },
  {
    id: "4",
    name: "Spider man",
    avatar: "",
    plan: "Student",
    amount: "৳149/mo",
    status: "Active",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    autoRenew: true,
  },
  {
    id: "5",
    name: "Arun roy",
    avatar: "",
    plan: "Premium",
    amount: "৳149/mo",
    status: "Cancelled",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    autoRenew: true,
  },
];
