import { userNotificationsAssets } from "./userNotificationsAssets"

export const notificationsFilters = ["All", "Music", "Social", "Rewards"]

export const notifications = [
  {
    id: "notif-1",
    group: "today",
    category: "MUSIC UPDATE",
    categoryFilter: "Music",
    categoryTone: "secondary",
    timestamp: "2m ago",
    message: "Neon-X just dropped a new single: 'Digital Pulse'. Listen now.",
    thumbnail: { type: "image", src: userNotificationsAssets.images.musicUpdateNeonX },
    unread: true,
  },
  {
    id: "notif-2",
    group: "today",
    category: "TICKET ALERT",
    categoryFilter: "Social",
    categoryTone: "primary",
    timestamp: "1h ago",
    message: "Early access for 'Synth City Live' tickets starts in 2 hours! Secure yours.",
    thumbnail: { type: "icon", src: userNotificationsAssets.icons.ticketAlert, bg: "#6f00be" },
    unread: false,
  },
  {
    id: "notif-3",
    group: "today",
    category: "SOCIAL",
    categoryFilter: "Social",
    categoryTone: "gradient",
    timestamp: "4h ago",
    message: "Fahim Islam started a new podcast series: 'The Future of Sound'.",
    thumbnail: { type: "image", src: userNotificationsAssets.images.socialFahimIslam },
    unread: false,
  },
  {
    id: "notif-4",
    group: "today",
    category: "REWARD",
    categoryFilter: "Rewards",
    categoryTone: "green",
    timestamp: "12h ago",
    messageParts: [
      { text: "You earned " },
      { text: "50 BeatX", className: "text-green-success" },
      { text: " Coins for your 7-day listening streak! 🪙" },
    ],
    thumbnail: { type: "icon", src: userNotificationsAssets.icons.rewardCoin, bg: "rgba(42,245,255,0.2)" },
    unread: true,
  },
  {
    id: "notif-5",
    group: "today",
    category: "SYSTEM",
    categoryFilter: "All",
    categoryTone: "neutral",
    timestamp: "1d ago",
    messageParts: [
      { text: "Your subscription " },
      { text: "'Premium Duo'", className: "text-light-gray" },
      { text: " successfully renewed." },
    ],
    thumbnail: { type: "icon", src: userNotificationsAssets.icons.systemBell, bg: "#2d3449" },
    unread: false,
  },
  {
    id: "notif-6",
    group: "yesterday",
    category: "MUSIC UPDATE",
    categoryFilter: "Music",
    categoryTone: "neutral",
    timestamp: "1d ago",
    message: "Acoustic Soul released a new playlist: 'Late Night Echoes'.",
    thumbnail: { type: "image", src: userNotificationsAssets.images.musicUpdateAcousticSoul },
    unread: false,
  },
]
