import { Space_Grotesk } from "next/font/google";
import { getServerSession } from "next-auth/next";
import "./globals.css";
import ProviderContainer from "@/Providers/ProviderContainer";
import { authOptions } from "@/lib/auth/authOptions";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ProviderContainer session={session}>
          {children}
        </ProviderContainer>
      </body>
    </html>
  );
}

