import { getServerSession } from "next-auth/next";
import "./globals.css";
import ProviderContainer from "@/Providers/ProviderContainer";
import { authOptions } from "@/lib/auth/authOptions";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <ProviderContainer session={session}>
          {children}
        </ProviderContainer>
      </body>
    </html>
  );
}

