import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import ProviderContainer from "@/Providers/ProviderContainer";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ProviderContainer>
          {children}
        </ProviderContainer>
      </body>
    </html>
  );
}

